baseurl = "https://stultus.in/"
title = "stultus"
theme = "stupidly-minimal"
languagecode = "en"
defaultcontentlanguage = "ml"

paginate = 20
canonifyurls = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
style = "monokai"

[params]
    author = "Hrishikesh Bhaskaran"
    tagline = "Developer / Flâneur / Storyteller"
    info = "Vice President of Engineering at [Entri](https://entri.me). Building things, telling stories, wandering through ideas. Interested in FOSS, language computing, privacy, and the places where technology meets culture."
    description = "Hrishikesh Bhaskaran. Developer, Flâneur, Storyteller."
    keywords = "developer,storyteller,foss,language-computing,personal"
    avatarurl = "img/hrishikesh_bhaskaran.jpg"
    logourl = "img/logo.png"
    email = "hrishi.kb@gmail.com"

    footercontent = "'It is our choices ... that show what we truly are, far more than our abilities' — Albus Dumbledore"

    hidecredits = false
    hidecopyright = false
    rtl = false
    custom_css = ["css/custom.css"]

# Menu links
[[menu.main]]
    name = "blog"
    weight = 1
    url  = "/post/"
[[menu.main]]
    name = "projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "now"
    weight = 3
    url = "/now/"
[[menu.main]]
    name = "about"
    weight = 4
    url = "/about/"
[[menu.main]]
    name = "notes"
    weight = 5
    url = "/notes/"
