#baseurl = "http://www.example.com"
title = "stultus"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "ml"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "stultus-in"
commentourl = "https://stultus-in.disqus.com/embed.js"
[markup.goldmark.renderer]
unsafe= true
[params]
    author = "Hrishikesh Bhaskaran"
    info = "Hacktivist | Programmer"
    description = "Hrishikesh Bhaskaran"
    keywords = "blog,developer,personal"
    avatarurl = "img/hrishi.jpg"

    #favicon_32 = "/img/favicon-32x32.png"
    #favicon_16 = "/img/favicon-16x16.png"

    footercontent = "'It is our choices ... that show what we truly are, far more than our abilities' - Albus Dumbledore"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/stultus/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/stultus/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/_stultus/"
[[params.social]]
    name = "Linkedin"
    icon ="fab fa-linkedin fa-2x"
    weight = 4
    url = "https://linkedin.com/in/stultus/"

[[params.social]]
    name = "Goodreads"
    icon ="fas fa-book fa-2x"
    weight = 5
    url = "https://goodreads.com/stultus/"


[[params.social]]
    name = "Instagram"
    icon ="fab fa-instagram fa-2x"
    weight = 6
    url = "https://instagram.com/in/stultusz/"
# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/post/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "notes"
    weight = 3
    url = "https://notes.stultus.in"
